name: build-monthly

on:
  workflow_dispatch:
  schedule:
     - cron: "1 0 1 * *"


env:
  DOTNET_VERSION: "8.0.403"

jobs:
  build:
    name: build-ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run
        run: dotnet run --project HackerNews.csproj
        working-directory: src/HackerNews/
        env:
            AppOption__AppPrivateKey: ${{ secrets.AppPrivateKey }}
            AppOption__HacknewsType: "Monthly"